# Reference: https://github.com/i3/i3/blob/next/etc/config
start-at-login = true
config-version = 2

# In i3, all workspaces are phantom
persistent-workspaces = []

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
[mode.main.binding]
    # focus: h j k l = left down up right
    alt-h =         'focus --boundaries-action wrap-around-the-workspace left'
    alt-j =         'focus --boundaries-action wrap-around-the-workspace down'
    alt-k =         'focus --boundaries-action wrap-around-the-workspace up'
    alt-l =         'focus --boundaries-action wrap-around-the-workspace right'

    # move windows
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # app launches
    alt-shift-b = 'exec-and-forget open -a "Safari"'
    alt-enter = 'exec-and-forget open -na "Ghostty"'
    alt-shift-n = 'exec-and-forget open -a "Notion"'
    alt-shift-f = 'exec-and-forget open -a "Finder"'
    alt-shift-m = 'exec-and-forget open -a "Spotify"'
    alt-shift-v = 'exec-and-forget open -a "System Settings"'

    # split/layout
    alt-slash = 'join-with down'
    alt-v = 'join-with right'

    alt-f = 'fullscreen'

    # alt-s = 'layout v_accordion'
    # alt-w = 'layout h_accordion'
    alt-e = 'layout tiles horizontal vertical'

    alt-shift-space = 'layout floating tiling'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-shift-c = 'reload-config'
    alt-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'
